name: employee_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  path: ^1.8.3
  bot_toast: ^4.1.3
  get_it: ^7.6.6
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  dart_std: ^0.0.7
  collection: ^1.18.0
  sqflite: ^2.3.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  freezed: ^2.4.6
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
